apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: controlplane
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    - name: rancher-ingressgateway
      namespace: cattle-system
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 1
          minReplicas: 1
        service:
          ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
      label:
        app: rancher-ingressgateway
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 1
          minReplicas: 1
  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  values:
    global:
      proxy:
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 16Mi