apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
spec:
  isCA: false
  commonName: rancher.example.com 
  secretName: tls-rancher-ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer 
    kind: ClusterIssuer
    group: cert-manager.io
